// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from "rxjs"
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined } from "../runtime"
import {
    OIDCAuthenticate
} from "../models"

export type OidcAuthenticateCreateRequest = {
    oIDCAuthenticate: OIDCAuthenticate
}

/**
 * no description
 */
export class OidcAuthenticateApi extends BaseAPI {
    /**
     */
    oidcAuthenticateCreate = ({ oIDCAuthenticate }: OidcAuthenticateCreateRequest): Observable<OIDCAuthenticate> => {
        throwIfNullOrUndefined(oIDCAuthenticate, "oidcAuthenticateCreate")

        const headers: HttpHeaders = {
            "Content-Type": "application/json",
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${ btoa(this.configuration.username + ":" + this.configuration.password) }` } : undefined)
        }

        return this.request<OIDCAuthenticate>({
            path: "/api/v1/oidc-authenticate/",
            method: "POST",
            headers,
            body: oIDCAuthenticate
        })
    };
}
