// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from "rxjs"
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined } from "../runtime"
import {
    Push
} from "../models"

export type PushCreateRequest = {
    push: Push
}

/**
 * no description
 */
export class PushApi extends BaseAPI {
    /**
     * Populates data through a push from Top, after which an \"In Progress\" state is created. A push from Top occurs when a case is added to an itinerary. After migrating from BWV to Zaken we can remove most of this push, and Top can do a simpler (and more generic) CREATE request for adding a state.
     */
    pushCreate = ({ push }: PushCreateRequest): Observable<Push> => {
        throwIfNullOrUndefined(push, "pushCreate")

        const headers: HttpHeaders = {
            "Content-Type": "application/json",
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${ btoa(this.configuration.username + ":" + this.configuration.password) }` } : undefined)
        }

        return this.request<Push>({
            path: "/api/v1/push/",
            method: "POST",
            headers,
            body: push
        })
    };
}
