// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from "rxjs"
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined } from "../runtime"
import {
    Test
} from "../models"

export type TestingUrlTryBrkApiCreateRequest = {
    test: Test
}

/**
 * no description
 */
export class TestingUrlApi extends BaseAPI {
    /**
     * request url
     */
    testingUrlTryBrkApiCreate = ({ test }: TestingUrlTryBrkApiCreateRequest): Observable<void> => {
        throwIfNullOrUndefined(test, "testingUrlTryBrkApiCreate")

        const headers: HttpHeaders = {
            "Content-Type": "application/json",
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${ btoa(this.configuration.username + ":" + this.configuration.password) }` } : undefined)
        }

        return this.request<void>({
            path: "/api/v1/testing-url/try_brk_api/",
            method: "POST",
            headers,
            body: test
        })
    };
}
