// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Address
 */
export type Address = {
    /**
     * @type {string}
     * @memberof Address
     */
    bag_id: string
    /**
     * @type {number}
     * @memberof Address
     */
    readonly id: number
    /**
     * @type {string}
     * @memberof Address
     */
    readonly full_address: string
    /**
     * @type {string}
     * @memberof Address
     */
    readonly street_name: string
    /**
     * @type {number}
     * @memberof Address
     */
    readonly number: number
    /**
     * @type {string}
     * @memberof Address
     */
    readonly suffix_letter: string
    /**
     * @type {string}
     * @memberof Address
     */
    readonly suffix: string
    /**
     * @type {string}
     * @memberof Address
     */
    readonly postal_code: string
    /**
     * @type {number}
     * @memberof Address
     */
    readonly lat: number
    /**
     * @type {number}
     * @memberof Address
     */
    readonly lng: number
}
