// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CaseTimelineThread
} from "./"

/**
 * @export
 * @interface CaseTimeline
 */
export type CaseTimeline = {
    /**
     * @type {number}
     * @memberof CaseTimeline
     */
    readonly id: number
    /**
     * @type {Array<CaseTimelineThread>}
     * @memberof CaseTimeline
     */
    readonly casetimelinethread_set: Array<CaseTimelineThread>
    /**
     * @type {string}
     * @memberof CaseTimeline
     */
    subject: string
    /**
     * @type {boolean}
     * @memberof CaseTimeline
     */
    is_done?: boolean
    /**
     * @type {number}
     * @memberof CaseTimeline
     */
    _case: number
}
