// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AnyType,
    CaseTimelineReaction
} from "./"

/**
 * @export
 * @interface CaseTimelineThread
 */
export type CaseTimelineThread = {
    /**
     * @type {number}
     * @memberof CaseTimelineThread
     */
    readonly id: number
    /**
     * @type {Array<CaseTimelineReaction>}
     * @memberof CaseTimelineThread
     */
    readonly casettimelinereaction_set: Array<CaseTimelineReaction>
    /**
     * @type {string}
     * @memberof CaseTimelineThread
     */
    readonly date: string
    /**
     * @type {{ [key: string]: AnyType; }}
     * @memberof CaseTimelineThread
     */
    parameters?: { [key: string]: AnyType }
    /**
     * @type {string}
     * @memberof CaseTimelineThread
     */
    notes?: string | null
    /**
     * @type {number}
     * @memberof CaseTimelineThread
     */
    subject: number
    /**
     * @type {Array<string>}
     * @memberof CaseTimelineThread
     */
    authors: Array<string>
}
