// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CaseState
 */
export type CaseState = {
    /**
     * @type {number}
     * @memberof CaseState
     */
    _case: number
    /**
     * @type {string}
     * @memberof CaseState
     */
    readonly status_name: string
    /**
     * @type {number}
     * @memberof CaseState
     */
    status: number
    /**
     * @type {string}
     * @memberof CaseState
     */
    state_date: string
    /**
     * @type {Array<string>}
     * @memberof CaseState
     */
    users: Array<string>
}
