// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CaseTimelineReaction
 */
export type CaseTimelineReaction = {
    /**
     * @type {number}
     * @memberof CaseTimelineReaction
     */
    readonly id: number
    /**
     * @type {string}
     * @memberof CaseTimelineReaction
     */
    comment: string
    /**
     * @type {string}
     * @memberof CaseTimelineReaction
     */
    readonly date: string
    /**
     * @type {number}
     * @memberof CaseTimelineReaction
     */
    timeline_item: number
    /**
     * @type {string}
     * @memberof CaseTimelineReaction
     */
    author: string
}
