// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ViolationEnum
} from "./"

/**
 * @export
 * @interface Debriefing
 */
export type Debriefing = {
    /**
     * @type {number}
     * @memberof Debriefing
     */
    readonly id: number
    /**
     * @type {number}
     * @memberof Debriefing
     */
    _case: number
    /**
     * @type {string}
     * @memberof Debriefing
     */
    author: string
    /**
     * @type {string}
     * @memberof Debriefing
     */
    readonly date_added: string
    /**
     * @type {string}
     * @memberof Debriefing
     */
    readonly date_modified: string
    /**
     * @type {ViolationEnum}
     * @memberof Debriefing
     */
    violation?: ViolationEnum
    /**
     * @type {string}
     * @memberof Debriefing
     */
    feedback: string
}
