// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    PermitTypeEnum
} from "./"

/**
 * @export
 * @interface DecosPermit
 */
export type DecosPermit = {
    /**
     * @type {boolean}
     * @memberof DecosPermit
     */
    permit_granted?: boolean
    /**
     * @type {PermitTypeEnum}
     * @memberof DecosPermit
     */
    permit_type?: PermitTypeEnum
    /**
     * @type {string}
     * @memberof DecosPermit
     */
    processed: string | null
    /**
     * @type {string}
     * @memberof DecosPermit
     */
    date_from: string | null
    /**
     * @type {string}
     * @memberof DecosPermit
     */
    date_to?: string | null
    /**
     * @type {string}
     * @memberof DecosPermit
     */
    decos_join_web_url?: string
}
