// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IndicatieBetHernBevelEnum,
    IndicatieCombiDwangbevelEnum,
    IndicatiePubliekrechtelijkEnum,
    SoortVorderingEnum
} from "./"

/**
 * @export
 * @interface Fine
 */
export type Fine = {
    /**
     * @type {string}
     * @memberof Fine
     */
    identificatienummer: string
    /**
     * @type {number}
     * @memberof Fine
     */
    vorderingnummer: number
    /**
     * @type {number}
     * @memberof Fine
     */
    jaar: number
    /**
     * @type {SoortVorderingEnum}
     * @memberof Fine
     */
    soort_vordering: SoortVorderingEnum
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving_soort_vordering: string
    /**
     * @type {IndicatiePubliekrechtelijkEnum}
     * @memberof Fine
     */
    indicatie_publiekrechtelijk: IndicatiePubliekrechtelijkEnum
    /**
     * @type {number}
     * @memberof Fine
     */
    subjectnr: number
    /**
     * @type {string}
     * @memberof Fine
     */
    opgemaaktenaam: string
    /**
     * @type {number}
     * @memberof Fine
     */
    subjectnr_opdrachtgever: number
    /**
     * @type {string}
     * @memberof Fine
     */
    opgemaaktenaam_opdrachtgever: string
    /**
     * @type {number}
     * @memberof Fine
     */
    runnr: number
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving_run: string
    /**
     * @type {string}
     * @memberof Fine
     */
    code_runwijze: string
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving_runwijze: string
    /**
     * @type {string}
     * @memberof Fine
     */
    dagtekening: string
    /**
     * @type {string}
     * @memberof Fine
     */
    vervaldatum: string
    /**
     * @type {IndicatieCombiDwangbevelEnum}
     * @memberof Fine
     */
    indicatie_combi_dwangbevel: IndicatieCombiDwangbevelEnum
    /**
     * @type {string}
     * @memberof Fine
     */
    notatekst: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    invorderingstatus: string
    /**
     * @type {IndicatieBetHernBevelEnum}
     * @memberof Fine
     */
    indicatie_bet_hern_bevel: IndicatieBetHernBevelEnum
    /**
     * @type {string}
     * @memberof Fine
     */
    landcode: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    kenteken: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    bonnummer: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    bedrag_opgelegd: string
    /**
     * @type {string}
     * @memberof Fine
     */
    bedrag_open_post_incl_rente: string
    /**
     * @type {string}
     * @memberof Fine
     */
    totaalbedrag_open_kosten: string
    /**
     * @type {string}
     * @memberof Fine
     */
    bedrag_open_rente: string
    /**
     * @type {string}
     * @memberof Fine
     */
    reden_opschorting: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving_1: string | null
    /**
     * @type {string}
     * @memberof Fine
     */
    omschrijving_2: string | null
}
