// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Case
} from "./"

/**
 * @export
 * @interface PaginatedCaseList
 */
export type PaginatedCaseList = {
    /**
     * @type {number}
     * @memberof PaginatedCaseList
     */
    count?: number
    /**
     * @type {string}
     * @memberof PaginatedCaseList
     */
    next?: string | null
    /**
     * @type {string}
     * @memberof PaginatedCaseList
     */
    previous?: string | null
    /**
     * @type {Array<Case>}
     * @memberof PaginatedCaseList
     */
    results?: Array<Case>
}
