// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PatchedAddress
 */
export type PatchedAddress = {
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    bag_id?: string
    /**
     * @type {number}
     * @memberof PatchedAddress
     */
    readonly id?: number
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    readonly full_address?: string
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    readonly street_name?: string
    /**
     * @type {number}
     * @memberof PatchedAddress
     */
    readonly number?: number
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    readonly suffix_letter?: string
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    readonly suffix?: string
    /**
     * @type {string}
     * @memberof PatchedAddress
     */
    readonly postal_code?: string
    /**
     * @type {number}
     * @memberof PatchedAddress
     */
    readonly lat?: number
    /**
     * @type {number}
     * @memberof PatchedAddress
     */
    readonly lng?: number
}
