// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PatchedCaseTimelineReaction
 */
export type PatchedCaseTimelineReaction = {
    /**
     * @type {number}
     * @memberof PatchedCaseTimelineReaction
     */
    readonly id?: number
    /**
     * @type {string}
     * @memberof PatchedCaseTimelineReaction
     */
    comment?: string
    /**
     * @type {string}
     * @memberof PatchedCaseTimelineReaction
     */
    readonly date?: string
    /**
     * @type {number}
     * @memberof PatchedCaseTimelineReaction
     */
    timeline_item?: number
    /**
     * @type {string}
     * @memberof PatchedCaseTimelineReaction
     */
    author?: string
}
