// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PatchedCaseState
 */
export type PatchedCaseState = {
    /**
     * @type {number}
     * @memberof PatchedCaseState
     */
    _case?: number
    /**
     * @type {string}
     * @memberof PatchedCaseState
     */
    readonly status_name?: string
    /**
     * @type {number}
     * @memberof PatchedCaseState
     */
    status?: number
    /**
     * @type {string}
     * @memberof PatchedCaseState
     */
    state_date?: string
    /**
     * @type {Array<string>}
     * @memberof PatchedCaseState
     */
    users?: Array<string>
}
