// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ViolationEnum
} from "./"

/**
 * @export
 * @interface PatchedDebriefing
 */
export type PatchedDebriefing = {
    /**
     * @type {number}
     * @memberof PatchedDebriefing
     */
    readonly id?: number
    /**
     * @type {number}
     * @memberof PatchedDebriefing
     */
    _case?: number
    /**
     * @type {string}
     * @memberof PatchedDebriefing
     */
    author?: string
    /**
     * @type {string}
     * @memberof PatchedDebriefing
     */
    readonly date_added?: string
    /**
     * @type {string}
     * @memberof PatchedDebriefing
     */
    readonly date_modified?: string
    /**
     * @type {ViolationEnum}
     * @memberof PatchedDebriefing
     */
    violation?: ViolationEnum
    /**
     * @type {string}
     * @memberof PatchedDebriefing
     */
    feedback?: string
}
