// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CaseState,
    PatchedAddress,
    PatchedCaseState
} from "./"

/**
 * @export
 * @interface PatchedCase
 */
export type PatchedCase = {
    /**
     * @type {number}
     * @memberof PatchedCase
     */
    readonly id?: number
    /**
     * @type {PatchedAddress}
     * @memberof PatchedCase
     */
    address?: PatchedAddress
    /**
     * @type {Array<PatchedCaseState>}
     * @memberof PatchedCase
     */
    case_states?: Array<PatchedCaseState>
    /**
     * @type {CaseState}
     * @memberof PatchedCase
     */
    readonly current_state?: CaseState
    /**
     * @type {string}
     * @memberof PatchedCase
     */
    identification?: string | null
    /**
     * @type {string}
     * @memberof PatchedCase
     */
    start_date?: string | null
    /**
     * @type {string}
     * @memberof PatchedCase
     */
    end_date?: string | null
}
