// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CaseTimelineThread
} from "./"

/**
 * @export
 * @interface PatchedCaseTimeline
 */
export type PatchedCaseTimeline = {
    /**
     * @type {number}
     * @memberof PatchedCaseTimeline
     */
    readonly id?: number
    /**
     * @type {Array<CaseTimelineThread>}
     * @memberof PatchedCaseTimeline
     */
    readonly casetimelinethread_set?: Array<CaseTimelineThread>
    /**
     * @type {string}
     * @memberof PatchedCaseTimeline
     */
    subject?: string
    /**
     * @type {boolean}
     * @memberof PatchedCaseTimeline
     */
    is_done?: boolean
    /**
     * @type {number}
     * @memberof PatchedCaseTimeline
     */
    _case?: number
}
