// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    HasBAndBPermitEnum,
    HasVacationRentalPermitEnum
} from "./"

/**
 * @export
 * @interface PermitCheckmark
 */
export type PermitCheckmark = {
    /**
     * @type {HasBAndBPermitEnum}
     * @memberof PermitCheckmark
     */
    has_b_and_b_permit: HasBAndBPermitEnum
    /**
     * @type {HasVacationRentalPermitEnum}
     * @memberof PermitCheckmark
     */
    has_vacation_rental_permit: HasVacationRentalPermitEnum
}
