// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PushState
 */
export type PushState = {
    /**
     * @type {string}
     * @memberof PushState
     */
    name: string
    /**
     * @type {string}
     * @memberof PushState
     */
    start_date: string
    /**
     * @type {string}
     * @memberof PushState
     */
    end_date?: string | null
    /**
     * @type {string}
     * @memberof PushState
     */
    gauge_date?: string | null
    /**
     * @type {string}
     * @memberof PushState
     */
    invoice_identification: string
}
