// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    PushState
} from "./"

/**
 * @export
 * @interface Push
 */
export type Push = {
    /**
     * @type {string}
     * @memberof Push
     */
    identification: string
    /**
     * @type {string}
     * @memberof Push
     */
    case_type: string
    /**
     * @type {string}
     * @memberof Push
     */
    bag_id: string
    /**
     * @type {string}
     * @memberof Push
     */
    start_date: string
    /**
     * @type {string}
     * @memberof Push
     */
    end_date?: string
    /**
     * @type {Array<PushState>}
     * @memberof Push
     */
    states?: Array<PushState>
}
