// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GeslachtsaanduidingEnum
} from "./"

/**
 * @export
 * @interface Resident
 */
export type Resident = {
    /**
     * @type {string}
     * @memberof Resident
     */
    geboortedatum: string
    /**
     * @type {GeslachtsaanduidingEnum}
     * @memberof Resident
     */
    geslachtsaanduiding: GeslachtsaanduidingEnum
    /**
     * @type {string}
     * @memberof Resident
     */
    geslachtsnaam: string
    /**
     * @type {string}
     * @memberof Resident
     */
    voorletters: string
    /**
     * @type {string}
     * @memberof Resident
     */
    voornamen: string
    /**
     * @type {string}
     * @memberof Resident
     */
    voorvoegsel_geslachtsnaam?: string
    /**
     * @type {string}
     * @memberof Resident
     */
    datum_begin_relatie_verblijadres: string
}
