// tslint:disable
/**
 * Zaken Backend Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AnyType
} from "./"

/**
 * @export
 * @interface TimelineUpdate
 */
export type TimelineUpdate = {
    /**
     * @type {string}
     * @memberof TimelineUpdate
     */
    thread_id: string
    /**
     * @type {string}
     * @memberof TimelineUpdate
     */
    subject: string
    /**
     * @type {{ [key: string]: AnyType; }}
     * @memberof TimelineUpdate
     */
    parameters: { [key: string]: AnyType } | null
    /**
     * @type {string}
     * @memberof TimelineUpdate
     */
    notes: string | null
    /**
     * @type {string}
     * @memberof TimelineUpdate
     */
    authors: string | null
}
